### PR TITLE
made all changes to convert initiatives to committees.

### PR DESCRIPTION
**Pull request by agango**

### CODE REVIEW

**Comment by joshuazweig** [comment]
@agango What are your thoughts on the scroll bar in each card? 

I think we can a) leave it as is b) shorten the descriptions or c) extend each card to a longer length

**Comment by agango** [comment]
Hmm so I added scrolling because I played around with the css for the card div for for a while but found it unresponsive, just couldn't get it to lengthen. It may have been something else though, I can look into it again. Also happy to shorten descriptions, but that's totally up to you guys

**Comment by joshuazweig** [comment]
I think I lean to merging now and I'll take a look at shortening
descriptions for a new PR.
If you agree, merge it

On Aug 29, 2016, at 8:28 AM, Abhiroop Gangopadhyay notifications@github.com
wrote:

Hmm so I added scrolling because I played around with the css for the card
div for for a while but found it unresponsive, just couldn't get it to
lengthen. It may have been something else though, I can look into it again.
Also happy to shorten descriptions, but that's totally up to you guys

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/coreatcu/website/pull/47#issuecomment-243109919, or mute
the thread

**Comment by agango** [comment]
lol wait no shortening the card lengths works. For some reason something was up with my browser last night and changes weren't getting updated. Made the changes. Btw not authorized to merge

**Pull request merged**
