### PR TITLE
Recruitment page

### PR DESCRIPTION
**Pull request by joshuazweig**

### CODE REVIEW

**Comment by sarasakowitz** [comment]
Can we try eliminating the paragraph breaks included right before the last sentence under "who we are" and "what we do"? (Basically pulling "If this sounds like you..." and "Up for the challenge..." into the paragraph right before those sentences)

**Comment by sarasakowitz** [comment]
Also can we insert the Nasdaq group shot right under the headline "Apply to be a Fall 2016 OCL"?

**Comment by sarasakowitz** [comment]
Also... do you think people will understand what the headline means? Or should we change it to "Join CORE" or something general like that?

**Comment by joshuazweig** [comment]
Comment 1: Would be inconsistent with the site design. I'd prefer to leave it as is. 

Comment 2 and 3: Resolved

**Pull request merged**
