### PR TITLE
quick fix for joanna

### PR DESCRIPTION
**Pull request by Howon**

### CODE REVIEW

**Comment by Howon** [comment]
infographic_-_logo_evolution

**Comment by jackiehluo** [comment]
Are the border radii different for some of the logos at the top?

**Comment by Howon** [comment]
I did not touch border radii
Just using whatever design team at Impulse gave me

**Comment by jackiehluo** [comment]
Or, I mean, for the logos at the top. Don't think they're part of this PR. Would be cool to get that standardized at some point!

**Comment by joshuazweig** [comment]
The CORE infographic linked from the Find out more button on the home page
is broken.

**Pull request merged**
